# Generated by Django 2.2 on 2019-04-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apercibimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.CharField(max_length=200)),
                ('periodo_academico', models.IntegerField()),
                ('curso', models.CharField(max_length=200)),
                ('unidad', models.CharField(max_length=200)),
                ('materia', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('horas_justificadas', models.CharField(max_length=200)),
                ('porcentaje_justificado', models.DecimalField(decimal_places=2, max_digits=6)),
                ('horas_injustificadas', models.CharField(max_length=200)),
                ('porcentaje_injustificado', models.DecimalField(decimal_places=2, max_digits=6)),
                ('retrasos', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
    ]
