# Generated by Django 2.2.1 on 2019-05-27 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apercibimientos', '0002_asignaturasespeciales'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AsignaturasEspeciales',
            new_name='AsignaturaEspecial',
        ),
    ]
