# Generated by Django 2.2 on 2019-04-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='validada',
            field=models.BooleanField(default=False),
        ),
    ]
