# Generated by Django 2.2 on 2019-04-27 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0002_visita_validada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='coordenadaX',
            new_name='latitud',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='coordenadaY',
            new_name='longitud',
        ),
    ]
