# Generated by Django 2.2 on 2019-04-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0003_auto_20190427_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visita',
            name='distancia',
        ),
        migrations.AddField(
            model_name='empresa',
            name='distancia',
            field=models.FloatField(default=0),
        ),
    ]
