# Generated by Django 2.2 on 2019-05-13 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0005_auto_20190512_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profesores', to='visitas.Profesor'),
        ),
    ]
